extends: google
globals:
  goog: false
env:
  browser: true
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  indent: [error, 2]
  max-len: [error, 120]
  no-new: warn
  quotes: [error, single, {"avoidEscape": true}]
  no-var: error
  curly: error
  no-floating-decimal: error
  no-unused-vars:
    - error
    - varsIgnorePattern: ^(?:(?:MDC(?:(?:[A-Z][a-z0-9]+)+)Adapter)|(?:(?:(?:[A-Z][a-z0-9]+)+)Type))$
  require-jsdoc: off
  valid-jsdoc: warn

  prefer-const: error
