language: node_js
branches:
  only:
  - master
matrix:
  include:
  - node_js: 7
    env:
    - SAUCE_USERNAME=ad-framework
    addons:
      sauce_connect: true
      jwt:
        secure: qB4wOf8LddpqWePTQiLUWpz9FuLm4UrNjwB5Q7gdlDzYjs46Rae19eZZxcNGantuknU6KvqBwshZtna44XTSI7uGBIe8oFvGHJn+TIi6pPwVS6EuBf/48z/pfz8hk7xEtWyqDvWRXx8vnZtav9533pCuRUjXdLsELjs0G82BGk2fdKpZ+SoPay+hp5CoGGHAV/FbA2eg9WjvoKRohhdl6BKOuRaGYjhWOWMwVlHCOAnFINqVZ9MgFQxJf0u93MQqhnOCAP6j8eLENAk7Hcezu65wfSG0G92SLkQMQ4gzb3hdDNq7bc40jj0cHOquDcHPmESS3AS7RsKYNLLpCdHTm22Bf51+45KR6FKKEV9cshrRyagmjCwmSOmDrFa/MWCI8dgbj5d0EUkE7JmlDTR64naUmuljOMLlOCeuIERdR92STnfZHRmlXAqD8CiYmCbkJ/sZvdMljRbka+rKvZcVkXm6qOnMws4CF8sczs3D5d+5WqepOGENAXFDkhjL4m8VGWlx7LoiF6T/DPULuKpgw7pY6b0+tP+E1TXK8pFdRG9YzWZKhWbVAuZ9Sei/WVzDqVZSA7M+4gkDi870uadUsYNUW+JIxkT1erP4royO8Sm7WD+6A32q6MSiHoFYkN294tg203w2iYuHJ/LMpVfNTpiaJInCwHeJn2EvUGByX64=
    after_success:
    - codecov
  - node_js: --lts
    env:
    - SAUCE_USERNAME=ad-framework
    addons:
      sauce_connect: true
      jwt:
        secure: qB4wOf8LddpqWePTQiLUWpz9FuLm4UrNjwB5Q7gdlDzYjs46Rae19eZZxcNGantuknU6KvqBwshZtna44XTSI7uGBIe8oFvGHJn+TIi6pPwVS6EuBf/48z/pfz8hk7xEtWyqDvWRXx8vnZtav9533pCuRUjXdLsELjs0G82BGk2fdKpZ+SoPay+hp5CoGGHAV/FbA2eg9WjvoKRohhdl6BKOuRaGYjhWOWMwVlHCOAnFINqVZ9MgFQxJf0u93MQqhnOCAP6j8eLENAk7Hcezu65wfSG0G92SLkQMQ4gzb3hdDNq7bc40jj0cHOquDcHPmESS3AS7RsKYNLLpCdHTm22Bf51+45KR6FKKEV9cshrRyagmjCwmSOmDrFa/MWCI8dgbj5d0EUkE7JmlDTR64naUmuljOMLlOCeuIERdR92STnfZHRmlXAqD8CiYmCbkJ/sZvdMljRbka+rKvZcVkXm6qOnMws4CF8sczs3D5d+5WqepOGENAXFDkhjL4m8VGWlx7LoiF6T/DPULuKpgw7pY6b0+tP+E1TXK8pFdRG9YzWZKhWbVAuZ9Sei/WVzDqVZSA7M+4gkDi870uadUsYNUW+JIxkT1erP4royO8Sm7WD+6A32q6MSiHoFYkN294tg203w2iYuHJ/LMpVfNTpiaJInCwHeJn2EvUGByX64=
    script: npm run pretest && npm run test:unit
